name: Build Artifacts

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Get latest release
      id: get-latest-release
      run: |
        latest_release=$(curl -s https://api.github.com/repos/Anuken/MindustryBuilds/releases/latest)
        release_tag=$(echo "$latest_release" | jq -r .tag_name)
        echo "::set-output name=release_tag::$release_tag"

    - name: Get my latest release
      id: get-my-latest-release
      run: |
        latest_release=$(curl -s https://api.github.com/repos/Cong0707/MindustryServerBuilds/releases/latest)
        release_tag=$(echo "$latest_release" | jq -r .tag_name)
        echo "::set-output name=release_tag::$release_tag"
        
    - name: Check for new release
      id: check-new-release
      run: |
        echo "LAST_RELEASE=${{ steps.get-my-latest-release.outputs.release_tag }}"
        echo "CURRENT_RELEASE=${{ steps.get-latest-release.outputs.release_tag }}"
        if [ "${{ steps.get-my-latest-release.outputs.release_tag }}" != "${{ steps.get-latest-release.outputs.release_tag }}" ]; then
          echo "New release detected."
          echo "::set-output name=new_release::true"
        else
          echo "No new release."
          echo "::set-output name=new_release::false"
        fi
        
    - name: Set up JDK 17
      if: steps.check-new-release.outputs.new_release == 'true'
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Set env
      if: steps.check-new-release.outputs.new_release == 'true'
      run: echo "RELEASE_VERSION=${{ steps.get-latest-release.outputs.release_tag }}" >> $GITHUB_ENV
    - name: Create artifacts
      if: steps.check-new-release.outputs.new_release == 'true'
      run: |
        git clone --depth=1 --branch=master https://github.com/Anuken/Mindustry
        cd Mindustry
        ./gradlew server:dist -Pbuildversion=-1 --stacktrace
        mv server/build/libs/server-release.jar server/build/libs/Mindustry-BE-Server-${RELEASE_VERSION}.jar
    - name: Upload server artifacts
      if: steps.check-new-release.outputs.new_release == 'true'
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: Mindustry/server/build/libs/Mindustry-BE-Server-${{ env.RELEASE_VERSION }}.jar
        tag: "${{ steps.get-latest-release.outputs.release_tag }}"
